name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  dio: ^5.0.3
  dio_cache_interceptor: ^3.4.0
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.0.14
  logging: ^1.1.1
  easy_localization: ^3.0.1
  flutter_pdfview: ^1.3.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/translations/